/*
 * Contains the list of available games
 */
 var _g = new Array();
 var _games;
 var _gamesCounter = -1;


// DEMO GAMES
_gamesCounter++;_g[_gamesCounter] = new Object();_g[_gamesCounter].name = 'Kung-Fu-Zen';_g[_gamesCounter].path = 'Zen.unity3d';_g[_gamesCounter].type = 'unity';_g[_gamesCounter].credits = 'Veronica, Dennis, Niklas, Christian';_g[_gamesCounter].instructions = 'Nail the moves to keep your points (be quick)';
_gamesCounter++;_g[_gamesCounter] = new Object();_g[_gamesCounter].name = 'Fall Into Shape';_g[_gamesCounter].path = 'FallIntoShape.unity3d';_g[_gamesCounter].type = 'unity';_g[_gamesCounter].credits = 'Bjarke Hou Kammersgaard, @bthj, @Edda_Lara, Jakob Melnyk and Jacob Grooss. Textures: bit.ly/1l62fve';_g[_gamesCounter].instructions = 'Use left, right, up & down to rotate the objects to make them fit into the holes. A&B controls the speed.';
_gamesCounter++;_g[_gamesCounter] = new Object();_g[_gamesCounter].name = 'Feed The Pig';_g[_gamesCounter].path = 'FeedThePig.unity3d';_g[_gamesCounter].type = 'unity';_g[_gamesCounter].credits = 'Art: Bjørn Madsen Martin Hansen Jakob Olsen; Audio: Lars Thomsen (& freesounds.org); Code: Asger Arentoft Lars Thomsen; Music: Kevin MacLeod';_g[_gamesCounter].instructions = 'You play a pig. Eat Snitches before they reach the exit. Snitches will avoid Poop. Tap Z repeatedly to eat Snitch. Tap X repeatedly to poop.';
_gamesCounter++;_g[_gamesCounter] = new Object();_g[_gamesCounter].name = 'Frost';_g[_gamesCounter].path = 'Frost.unity3d';_g[_gamesCounter].type = 'unity';_g[_gamesCounter].credits = 'Emma Vig,  Zhiruo Dong, Victor Apihtin, Peter Ellehammer Kristensen, Michał Królikowski, (Alex Korach)';_g[_gamesCounter].instructions = 'Use ARROW KEYS to select options in the story, and A/B to confirm.';
_gamesCounter++;_g[_gamesCounter] = new Object();_g[_gamesCounter].name = 'ITU Digital Hand-In Upload Simulator';_g[_gamesCounter].path = 'ituDigitalHandInUploadSimulator2014.unity3d';_g[_gamesCounter].type = 'unity';_g[_gamesCounter].credits = 'Adan, Alessio, Ea, Marco, @vincependrell';_g[_gamesCounter].instructions = '< & > to move.';
_gamesCounter++;_g[_gamesCounter] = new Object();_g[_gamesCounter].name = 'Cave Rescue';_g[_gamesCounter].path = 'MazeGame.unity3d';_g[_gamesCounter].type = 'unity';_g[_gamesCounter].credits = 'Lau Nielsen, Mia Mai Graabæk, Frederik Frydenberg, Kasper Roskvist Andersen, Miki Anthony';_g[_gamesCounter].instructions = 'You only have 1 min to help the lost children out of the maze before the darkness consumes you. Deliver them at the white exit.';
_gamesCounter++;_g[_gamesCounter] = new Object();_g[_gamesCounter].name = 'Boredom';_g[_gamesCounter].path = 'DrugGame.unity3d';_g[_gamesCounter].type = 'unity';_g[_gamesCounter].credits = 'Andrea Catalini, Sandra Madsen, Paulo Oliveira, Till Riemer, Tanel Teinemaa';_g[_gamesCounter].instructions = 'Arrows to move, X to have fun';
_gamesCounter++;_g[_gamesCounter] = new Object();_g[_gamesCounter].name = 'Uncle Joon\'s Farm';_g[_gamesCounter].path = 'unclejonsfarm.unity3d';_g[_gamesCounter].type = 'unity';_g[_gamesCounter].credits = '@kfap, @awie, @mvie';_g[_gamesCounter].instructions = 'Kill the animals in the right order, shown at the top. Press A(X) to shoot and B(C) to sprint.';
_gamesCounter++;_g[_gamesCounter] = new Object();_g[_gamesCounter].name = 'Cave In on the Caveman';_g[_gamesCounter].path = 'Cave%20In%20on%20the%20Caveman.unity3d';_g[_gamesCounter].type = 'unity';_g[_gamesCounter].credits = 'Trond Glomnes, Eva-Lis Larsen Nugent & @timskafte';_g[_gamesCounter].instructions = 'Run through the cave, avoid loose rocks and obstacles. Move with the ARROWKEYS, and change gravity with X and Z.';