/*
 * Contains the list of available games
 */
 var _g = new Array();
 var _games;
 var _gamesCounter = -1;


// DEMO GAMES
_gamesCounter++;_g[_gamesCounter] = new Object();_g[_gamesCounter].name = 'Unity Demo Level 1';_g[_gamesCounter].path = 'UnityDemoLevel1.unity3d';_g[_gamesCounter].type = 'unity';_g[_gamesCounter].credits = '@joonturbo, @pyjamads';_g[_gamesCounter].instructions = 'Jump on each others heads.';
_gamesCounter++;_g[_gamesCounter] = new Object();_g[_gamesCounter].name = 'Unity Demo Level 2';_g[_gamesCounter].path = 'UnityDemoLevel2.unity3d';_g[_gamesCounter].type = 'unity';_g[_gamesCounter].credits = '@joonturbo, @pyjamads';_g[_gamesCounter].instructions = 'Jump on each others heads.';
_gamesCounter++;_g[_gamesCounter] = new Object();_g[_gamesCounter].name = 'Unity Demo Level 3';_g[_gamesCounter].path = 'UnityDemoLevel3.unity3d';_g[_gamesCounter].type = 'unity';_g[_gamesCounter].credits = '@joonturbo, @pyjamads';_g[_gamesCounter].instructions = 'Jump on each others heads.';
_gamesCounter++;_g[_gamesCounter] = new Object();_g[_gamesCounter].name = 'Dot Collector Extreme: Supreme Block Commanders';_g[_gamesCounter].path = 'andersgame.swf';_g[_gamesCounter].type = 'flash';_g[_gamesCounter].credits = '@norwigi';_g[_gamesCounter].instructions = 'Collect the dots and bring them home. Pressing A may have unforseen consequenses.';

// SUBMISSIONS
_gamesCounter++;_g[_gamesCounter] = new Object();_g[_gamesCounter].name = 'Sonar';_g[_gamesCounter].path = 'Sonar.unity3d';_g[_gamesCounter].type = 'unity';_g[_gamesCounter].credits = '@SimonEngelsted   ';_g[_gamesCounter].instructions = 'A: Sonar, B: Shoot';
_gamesCounter++;_g[_gamesCounter] = new Object();_g[_gamesCounter].name = '4sail';_g[_gamesCounter].path = 'foursail.swf';_g[_gamesCounter].type = 'flash';_g[_gamesCounter].credits = 'Ethan Kennerly';_g[_gamesCounter].instructions = 'Left/Right Steer. J/L Main left/right. D Head left. F Head right. One minute race!';
_gamesCounter++;_g[_gamesCounter] = new Object();_g[_gamesCounter].name = 'FussBall - ChainJamDemo Style';_g[_gamesCounter].path = 'FussBall.unity3d';_g[_gamesCounter].type = 'unity';_g[_gamesCounter].credits = '@pyjamads - #chainjam';_g[_gamesCounter].instructions = 'Run into the ball to make it bounce towards enemy goal, use buttons to dash. Black/Pink is team 1. Green/Blue is team 2.';
_gamesCounter++;_g[_gamesCounter] = new Object();_g[_gamesCounter].name = 'Fugg';_g[_gamesCounter].path = 'fugg.unity3d';_g[_gamesCounter].type = 'unity';_g[_gamesCounter].credits = '@joonturbo';_g[_gamesCounter].instructions = 'FILL SCREEN WITH YOUR COLOR. HIGHEST % WILL GET POINTS.';
_gamesCounter++;_g[_gamesCounter] = new Object();_g[_gamesCounter].name = 'Take Me To The Future';_g[_gamesCounter].path = 'TMTTF.swf';_g[_gamesCounter].type = 'flash';_g[_gamesCounter].credits = 'Nils Iver Holtar';_g[_gamesCounter].instructions = 'A: Shoot, B: Lay Bombs. Only the player in the future can move and perform an action. Try to hit the other players!';
_gamesCounter++;_g[_gamesCounter] = new Object();_g[_gamesCounter].name = 'Color Bounce';_g[_gamesCounter].path = 'ColorBounce.unity3d';_g[_gamesCounter].type = 'unity';_g[_gamesCounter].credits = 'Karrman corp present a Game made by tal swedish person';_g[_gamesCounter].instructions = 'Balls can be moved left and right and down. Last player on field wins';
_gamesCounter++;_g[_gamesCounter] = new Object();_g[_gamesCounter].name = 'Mages and Rogues';_g[_gamesCounter].path = 'Export.unity3d';_g[_gamesCounter].type = 'unity';_g[_gamesCounter].credits = '@joe_babz @dpruzi';_g[_gamesCounter].instructions = 'Mages VS Rogues! A = Attack, B = Block';
_gamesCounter++;_g[_gamesCounter] = new Object();_g[_gamesCounter].name = 'Climb, Freeze.';_g[_gamesCounter].path = 'ClimbFreeze2.unity3d';_g[_gamesCounter].type = 'unity';_g[_gamesCounter].credits = 'Guido Zuidhof';_g[_gamesCounter].instructions = '';
_gamesCounter++;_g[_gamesCounter] = new Object();_g[_gamesCounter].name = 'Shootah - RAVEGING GNOMES';_g[_gamesCounter].path = 'Shootah.unity3d';_g[_gamesCounter].type = 'unity';_g[_gamesCounter].credits = '@pyjamads - #chainjam';_g[_gamesCounter].instructions = 'Use your gnome to pick up presents! Fire magical balls at other gnomes to incapacitate them for a while!';
_gamesCounter++;_g[_gamesCounter] = new Object();_g[_gamesCounter].name = 'Quiz?';_g[_gamesCounter].path = 'Quiz.unity3d';_g[_gamesCounter].type = 'unity';_g[_gamesCounter].credits = 'Simon Engelsted';_g[_gamesCounter].instructions = 'Use the left stick to answer questions';
_gamesCounter++;_g[_gamesCounter] = new Object();_g[_gamesCounter].name = 'Foosball';_g[_gamesCounter].path = 'Foosball.unity3d';_g[_gamesCounter].type = 'unity';_g[_gamesCounter].credits = 'Game by Lars Bindslev Lars Bindslev, music by Questiion (Freesound.org)';_g[_gamesCounter].instructions = '';
_gamesCounter++;_g[_gamesCounter] = new Object();_g[_gamesCounter].name = 'CURVES';_g[_gamesCounter].path = 'curves.unity3d';_g[_gamesCounter].type = 'unity';_g[_gamesCounter].credits = '@poppmattsson & @ofktoubro';_g[_gamesCounter].instructions = 'Turn left or right and dont hit anything. Score points by being the last player alive.';
_gamesCounter++;_g[_gamesCounter] = new Object();_g[_gamesCounter].name = 'Sidewalkers';_g[_gamesCounter].path = 'Sidewalker_RC4.unity3d';_g[_gamesCounter].type = 'unity';_g[_gamesCounter].credits = 'Adan, Jan, Paulo, Till';_g[_gamesCounter].instructions = 'Eliminate! Button 1/2 to turn, Left/Right to move, Up to attack';
_gamesCounter++;_g[_gamesCounter] = new Object();_g[_gamesCounter].name = 'Gauge';_g[_gamesCounter].path = 'gauge.swf';_g[_gamesCounter].type = 'flash';_g[_gamesCounter].credits = 'Joel Lauener';_g[_gamesCounter].instructions = 'Single button game, use only UP.';
_gamesCounter++;_g[_gamesCounter] = new Object();_g[_gamesCounter].name = 'Pro Spaceship Slalom 2013: Urban Barrel Roll Edition';_g[_gamesCounter].path = 'PlaneJam%20BarrelRoll%20Edition.unity3d';_g[_gamesCounter].type = 'unity';_g[_gamesCounter].credits = 'Victor (@Xroft666), Vince (@VincePendrell), Alessio (no twitter :/)';_g[_gamesCounter].instructions = 'Nail the 3 rings to get a point.';
_gamesCounter++;_g[_gamesCounter] = new Object();_g[_gamesCounter].name = 'Survive!';_g[_gamesCounter].path = 'Survive.unity3d';_g[_gamesCounter].type = 'unity';_g[_gamesCounter].credits = 'Vince (@VincePendrell, using Chain Jam sample assets)';_g[_gamesCounter].instructions = 'Survive for a minute and get points!';
_gamesCounter++;_g[_gamesCounter] = new Object();_g[_gamesCounter].name = 'Bouncing Strawberry Unicorn';_g[_gamesCounter].path = 'BouncingStrawberryUnicorn.unity3d';_g[_gamesCounter].type = 'unity';_g[_gamesCounter].credits = 'Trond Glomnes, Tanel Teinemaa, Sandra Madsen';_g[_gamesCounter].instructions = 'Push the opponents off the platform!';
_gamesCounter++;_g[_gamesCounter] = new Object();_g[_gamesCounter].name = 'Local Council';_g[_gamesCounter].path = 'LocalCouncil.swf';_g[_gamesCounter].type = 'flash';_g[_gamesCounter].credits = '@1000tongues';_g[_gamesCounter].instructions = 'Vote yea on the propositions connecting to your colour. Councilpersons! There can be only one! Or none.';
_gamesCounter++;_g[_gamesCounter] = new Object();_g[_gamesCounter].name = 'territory';_g[_gamesCounter].path = 'territory.unity3d';_g[_gamesCounter].type = 'unity';_g[_gamesCounter].credits = 'mrt';_g[_gamesCounter].instructions = 'Increase your territory by stealing from others. Surround areas for quick gains. Acquire bombs by surrounding them, trigger with A/B.';
_gamesCounter++;_g[_gamesCounter] = new Object();_g[_gamesCounter].name = 'Ringside';_g[_gamesCounter].path = 'RingSide.unity3d';_g[_gamesCounter].type = 'unity';_g[_gamesCounter].credits = 'The Brohirim';_g[_gamesCounter].instructions = 'Shoot balls in middle to charge. Absorb charged balls. Non-charged balls kills. ';
_gamesCounter++;_g[_gamesCounter] = new Object();_g[_gamesCounter].name = 'One Direction';_g[_gamesCounter].path = 'oneDirection.unity3d';_g[_gamesCounter].type = 'unity';_g[_gamesCounter].credits = '@VildNinja';_g[_gamesCounter].instructions = 'Move in your own direction, or follow others to move in theirs. Collect the sparkling dots!';
_gamesCounter++;_g[_gamesCounter] = new Object();_g[_gamesCounter].name = 'Bitchin\' Pigeons';_g[_gamesCounter].path = 'pigeons.unity3d';_g[_gamesCounter].type = 'unity';_g[_gamesCounter].credits = '@lolinc_, @Mikianthony, Emma Vig, @cogitonovus';_g[_gamesCounter].instructions = 'Get on top of those pigeons\'!';
_gamesCounter++;_g[_gamesCounter] = new Object();_g[_gamesCounter].name = 'Hamster Survival';_g[_gamesCounter].path = 'BalanceSurvival.unity3d';_g[_gamesCounter].type = 'unity';_g[_gamesCounter].credits = 'Célia Gironnet - lucieviatge.com - flexroman.tumblr.com - tom-victor.com/';_g[_gamesCounter].instructions = 'Roll around, do not fall, drop bombs to annoy your friends. You only have two lives !';
_gamesCounter++;_g[_gamesCounter] = new Object();_g[_gamesCounter].name = 'ORB';_g[_gamesCounter].path = 'ORB.unity3d';_g[_gamesCounter].type = 'unity';_g[_gamesCounter].credits = '@goyalanshul and @A_R_Green_00';_g[_gamesCounter].instructions = 'Collect all orbs. A button to Shoot, B to teleport. Wait for the cooldown before doing it again. On hit, player looses all collected orbs.';
_gamesCounter++;_g[_gamesCounter] = new Object();_g[_gamesCounter].name = 'Jameleon';_g[_gamesCounter].path = 'jameleon.swf';_g[_gamesCounter].type = 'flash';_g[_gamesCounter].credits = 'Andrei Livadariu & Nina Croitoru (@ninacroitoru) Sound: Starlord827 and Kwazi @ freesound.org';_g[_gamesCounter].instructions = 'Hit each other with your tongues. Collect powerups for speed.';
_gamesCounter++;_g[_gamesCounter] = new Object();_g[_gamesCounter].name = 'Tail Chase';_g[_gamesCounter].path = 'Tail Chase.htm';_g[_gamesCounter].type = 'html5';_g[_gamesCounter].credits = 'Johannes Wärn';_g[_gamesCounter].instructions = 'Left/Right: Turn';
_gamesCounter++;_g[_gamesCounter] = new Object();_g[_gamesCounter].name = 'Arkoh';_g[_gamesCounter].path = 'arkoh.swf';_g[_gamesCounter].type = 'flash';_g[_gamesCounter].credits = '@Mikianthony';_g[_gamesCounter].instructions = 'Take the ball and keep it!';
_gamesCounter++;_g[_gamesCounter] = new Object();_g[_gamesCounter].name = 'High Rise Hovercraft';_g[_gamesCounter].path = 'hoverbounce.unity3d';_g[_gamesCounter].type = 'unity';_g[_gamesCounter].credits = '@amazingrolo @jonbro & sean (Lucky Frame)';_g[_gamesCounter].instructions = 'Knock hovers off building. A to boost, B to brake';
_gamesCounter++;_g[_gamesCounter] = new Object();_g[_gamesCounter].name = 'The God Complex';_g[_gamesCounter].path = 'IamGod.unity3d';_g[_gamesCounter].type = 'unity';_g[_gamesCounter].credits = '@MarcPilgaard';_g[_gamesCounter].instructions = 'Its an unfair game. In order to win, push buttons.';
_gamesCounter++;_g[_gamesCounter] = new Object();_g[_gamesCounter].name = 'Belseplupp';_g[_gamesCounter].path = 'loot.swf';_g[_gamesCounter].type = 'flash';_g[_gamesCounter].credits = '@reallyolle, @salkinitzor, @grapefrukt';_g[_gamesCounter].instructions = 'The Boss is dead. Get that loot into your corner!';
_gamesCounter++;_g[_gamesCounter] = new Object();_g[_gamesCounter].name = 'Dinosaur Astronauts';_g[_gamesCounter].path = 'DinosaurAstronauts.unity3d';_g[_gamesCounter].type = 'unity';_g[_gamesCounter].credits = '@Robin_B coding, design, gameplay @DanMurdochMusic audio.';_g[_gamesCounter].instructions = 'Left + Right to steer your Space Dino. Collect most things by looping around them.';
_gamesCounter++;_g[_gamesCounter] = new Object();_g[_gamesCounter].name = 'Multiaim';_g[_gamesCounter].path = 'multiaim-gh-pages/index.html';_g[_gamesCounter].type = 'html5';_g[_gamesCounter].credits = 'Iwan Gabovitch @qubodup (Music by DaveN)';_g[_gamesCounter].instructions = 'Get the targets of your color!';
_gamesCounter++;_g[_gamesCounter] = new Object();_g[_gamesCounter].name = 'Parachute Panic';_g[_gamesCounter].path = 'ParachutePanic.unity3d';_g[_gamesCounter].type = 'unity';_g[_gamesCounter].credits = '@Adam_DBS';_g[_gamesCounter].instructions = 'Hold the parachute the longest. hold it at the end for extra points!';
_gamesCounter++;_g[_gamesCounter] = new Object();_g[_gamesCounter].name = 'Yeoman Percivals Last Flight';_g[_gamesCounter].path = 'PercivalsLastFlight.unity3d';_g[_gamesCounter].type = 'unity';_g[_gamesCounter].credits = 'Calle Leppäjoki and Smilla the cat.';_g[_gamesCounter].instructions = 'UP & DOWN';
_gamesCounter++;_g[_gamesCounter] = new Object();_g[_gamesCounter].name = 'Captain Elliot\'s Treasure';_g[_gamesCounter].path = 'Submission.unity3d';_g[_gamesCounter].type = 'unity';_g[_gamesCounter].credits = '@UffeFlarup';_g[_gamesCounter].instructions = 'Get to the treasure at center of the maze. Beware of the lava, if you fall into it you have to start over.';
_gamesCounter++;_g[_gamesCounter] = new Object();_g[_gamesCounter].name = 'PLOPong';_g[_gamesCounter].path = 'PLOPong.unity3d';_g[_gamesCounter].type = 'unity';_g[_gamesCounter].credits = 'Andrew Ogden, Nic Vasconcellos, Michael Downing';_g[_gamesCounter].instructions = 'Throw the ball in the other team\'s cups';
_gamesCounter++;_g[_gamesCounter] = new Object();_g[_gamesCounter].name = 'SpaceShip & Lasers';_g[_gamesCounter].path = 'SpaceShipLasers.unity3d';_g[_gamesCounter].type = 'unity';_g[_gamesCounter].credits = '@ManyEdges | Music courtesy of www.playonloop.com';_g[_gamesCounter].instructions = 'A to fire, B to dash. Hit the others to score points.';
_gamesCounter++;_g[_gamesCounter] = new Object();_g[_gamesCounter].name = 'Brick Jam';_g[_gamesCounter].path = 'BrickJam.unity3d';_g[_gamesCounter].type = 'unity';_g[_gamesCounter].credits = 'Camilla Horne ; Music by hektikmusic';_g[_gamesCounter].instructions = 'You consist of bricks, which work both as health and ammunition. Bricks are lost by shooting, being hit, or bumping into something.';
_gamesCounter++;_g[_gamesCounter] = new Object();_g[_gamesCounter].name = '#atomicfirstangelracing';_g[_gamesCounter].path = 'atomicfirstangelracing.unity3d';_g[_gamesCounter].type = 'unity';_g[_gamesCounter].credits = '@mortenmygind';_g[_gamesCounter].instructions = 'Angels driving full speed.   Pass as many white gates as possible.   L/R to turn L/R.';
_gamesCounter++;_g[_gamesCounter] = new Object();_g[_gamesCounter].name = 'Complete the Potion';_g[_gamesCounter].path = 'complete/index.html';_g[_gamesCounter].type = 'html5';_g[_gamesCounter].credits = 'Arthur, Oliver, Wilson';_g[_gamesCounter].instructions = 'Bring 3 correct ingredients to win a game.';
_gamesCounter++;_g[_gamesCounter] = new Object();_g[_gamesCounter].name = 'Fake Mustache';_g[_gamesCounter].path = 'FakeMustache.swf';_g[_gamesCounter].type = 'flash';_g[_gamesCounter].credits = '@Jelcynek';_g[_gamesCounter].instructions = 'Every moustache need to be well-groomed, even the fake one. Follow the on-screen hints to give your moustache great look.';
_gamesCounter++;_g[_gamesCounter] = new Object();_g[_gamesCounter].name = 'Townquest';_g[_gamesCounter].path = 'Townquest.swf';_g[_gamesCounter].type = 'flash';_g[_gamesCounter].credits = 'Xavier V Lafont';_g[_gamesCounter].instructions = 'Hold Action1 to command your soldiers! Release Action1 to make them stay! While commanding soldiers, move into a town to capture it!';
_gamesCounter++;_g[_gamesCounter] = new Object();_g[_gamesCounter].name = 'Hammertennis (ChainJam Edition)';_g[_gamesCounter].path = 'chainjam%20hammertennis.unity3d';_g[_gamesCounter].type = 'unity';_g[_gamesCounter].credits = 'Tobias Wehrum (@tolicious), Moritz Ufer, Kevin MacLeod, The Northern Block';_g[_gamesCounter].instructions = 'Keep balls as long as possible in your area.';
_gamesCounter++;_g[_gamesCounter] = new Object();_g[_gamesCounter].name = 'Flashlight Tag';_g[_gamesCounter].path = 'Flashlight%20Tag%20Chain.unity3d';_g[_gamesCounter].type = 'unity';_g[_gamesCounter].credits = '@jkoleszar';_g[_gamesCounter].instructions = 'Spot the other spheres with your flashlight (A) and tag them with B + the direction that matches their color.';
_gamesCounter++;_g[_gamesCounter] = new Object();_g[_gamesCounter].name = 'Four v. Horde';_g[_gamesCounter].path = 'main.swf';_g[_gamesCounter].type = 'flash';_g[_gamesCounter].credits = 'Game by @neokabuto, Music is Electric Fish by Mana Junkie, SFX originally by GregsMedia and Mike Koenig';_g[_gamesCounter].instructions = 'Move with directional keys, shoot with action key 1. Points are awarded based on kills. Avoid zombies.';
_gamesCounter++;_g[_gamesCounter] = new Object();_g[_gamesCounter].name = 'Zap Attack!';_g[_gamesCounter].path = 'ZapAttack.unity3d';_g[_gamesCounter].type = 'unity';_g[_gamesCounter].credits = 'Nic Vasconcellos';_g[_gamesCounter].instructions = 'Alternate button presses to build static. Left/Right - Move, X - Zap. First to 3.';
_gamesCounter++;_g[_gamesCounter] = new Object();_g[_gamesCounter].name = 'UkuLady: Possessed Fingers Strum Together!';_g[_gamesCounter].path = 'UkuLady.unity3d';_g[_gamesCounter].type = 'unity';_g[_gamesCounter].credits = 'Game by K Shonibare-Lewis (@glassdevil) Thanks to Martin Fasterholdt for code help and Simon Nielsen for finding the notes.';_g[_gamesCounter].instructions = 'Move your finger to the correct note. Try and play a chord together. Anyone can strum at any time, but correct chords give the most points.';
_gamesCounter++;_g[_gamesCounter] = new Object();_g[_gamesCounter].name = 'jump \'em over';_g[_gamesCounter].path = 'chainjam.swf';_g[_gamesCounter].type = 'flash';_g[_gamesCounter].credits = 'programming : alihassan @alythephantom  | art : Jay Daniel';_g[_gamesCounter].instructions = 'use direction keys to move , jump over other players to earn points ';
_gamesCounter++;_g[_gamesCounter] = new Object();_g[_gamesCounter].name = 'Space Skullduggery';_g[_gamesCounter].path = 'PalaRogue_ChainJam.swf';_g[_gamesCounter].type = 'flash';_g[_gamesCounter].credits = 'PalaRogue Games (David Blosser and Pamela Vargas) Music: http://www.freesfx.co.uk';_g[_gamesCounter].instructions = 'Fire at other players to keep them from collecting the CHAINJAM crates. Collect to score.';
_gamesCounter++;_g[_gamesCounter] = new Object();_g[_gamesCounter].name = 'A Brief History of the World';_g[_gamesCounter].path = 'bhow/index.html';_g[_gamesCounter].type = 'html5';_g[_gamesCounter].credits = 'Karl Flodin, Pontus Ullbors, Anders Larsson, Kristian Brodal, Gustav Rangmar, David Norberg, Petter Henriksson';_g[_gamesCounter].instructions = 'Lead your armies and crush your enemies through the ages as one of four unique civilizations. Arrows to move, action buttons to choose tech.';
_gamesCounter++;_g[_gamesCounter] = new Object();_g[_gamesCounter].name = 'Baguette Hunt';_g[_gamesCounter].path = 'BaguetteHunt/index.html';_g[_gamesCounter].type = 'html5';_g[_gamesCounter].credits = 'Art: Jimmy Laskowski; Music: Maria Önnberg; Code: Jonas Alenius, Alexander Hulander';_g[_gamesCounter].instructions = 'Action button 1 = Move right when you get to next intersection (all you can do). Colliding with others = 180 degree turn. Eat all baguettes!';
_gamesCounter++;_g[_gamesCounter] = new Object();_g[_gamesCounter].name = 'Space Cattles';_g[_gamesCounter].path = 'Space%20Cattles.unity3d';_g[_gamesCounter].type = 'unity';_g[_gamesCounter].credits = 'Game by @dreamfeeel , Paul MacAodh, and music by Syd Dale & Paddy Kingsland, Moos by all the lovely cows of freesound';_g[_gamesCounter].instructions = 'They call you the Space Cowboys: hold \'A\' to charge and let go to fire your lasso at as many cattle as you can, and \'B\' to reign them in.';
_gamesCounter++;_g[_gamesCounter] = new Object();_g[_gamesCounter].name = 'Spin Cycle Supreme';_g[_gamesCounter].path = 'SpinCycleSupreme.swf';_g[_gamesCounter].type = 'flash';_g[_gamesCounter].credits = 'CODE/DESIGN - @netgrind ART - @kelvinput';_g[_gamesCounter].instructions = 'RIGHT-clockwise LEFT-counterclockwise ACTION1-speedup GOAL-rotate to touch the same colored wall as it passes';
// DO NOT ADD THIS GAME (TALK TO JOON)
_gamesCounter++;_g[_gamesCounter] = new Object();_g[_gamesCounter].name = 'HiFiveBouncer';_g[_gamesCounter].path = 'HiFiveGame.swf';_g[_gamesCounter].type = 'flash';_g[_gamesCounter].credits = '@esquilaxgames: @guillewaitzel,@danidabate,@javiwaitzel, pijitas.tumblr.com';_g[_gamesCounter].instructions = 'Give the bouncer a H5, use down,left and right to hit his hands. Have fun and get into the best electronic party!!!';
_gamesCounter++;_g[_gamesCounter] = new Object();_g[_gamesCounter].name = 'New Rule';_g[_gamesCounter].path = 'newRule.unity3d';_g[_gamesCounter].type = 'unity';_g[_gamesCounter].credits = '@LauKorsgaard';_g[_gamesCounter].instructions = 'Push buttons. Generate rule. Obey the rule';
_gamesCounter++;_g[_gamesCounter] = new Object();_g[_gamesCounter].name = 'Kanako Gallop';_g[_gamesCounter].path = 'KanakoGallop.unity3d';_g[_gamesCounter].type = 'unity';_g[_gamesCounter].credits = 'Jesper Taxbøl, Kanako';_g[_gamesCounter].instructions = 'Use arrowkeys to get past the goalline.';
_gamesCounter++;_g[_gamesCounter] = new Object();_g[_gamesCounter].name = 'Elektromagnet';_g[_gamesCounter].path = 'Elektromagnet.unity3d';_g[_gamesCounter].type = 'unity';_g[_gamesCounter].credits = 'Eli Delventhal @daemonpants';_g[_gamesCounter].instructions = 'Press your button to toggle magnetic polarity. Go up!';
_gamesCounter++;_g[_gamesCounter] = new Object();_g[_gamesCounter].name = 'QuadElevateModulator';_g[_gamesCounter].path = 'qem.unity3d';_g[_gamesCounter].type = 'unity';_g[_gamesCounter].credits = 'Jannick Hynding Petersen, Michal Krolikowski & Niels Justesen';_g[_gamesCounter].instructions = 'Activate your elevating modulators!';
_gamesCounter++;_g[_gamesCounter] = new Object();_g[_gamesCounter].name = 'Laser Arena';_g[_gamesCounter].path = 'LaserArena.unity3d';_g[_gamesCounter].type = 'unity';_g[_gamesCounter].credits = 'Tilman Schmidt (@KeyMaster_)';_g[_gamesCounter].instructions = 'Left/Right - Steer, Up/A - Shoot, Down - Backward';
_gamesCounter++;_g[_gamesCounter] = new Object();_g[_gamesCounter].name = 'Chain Brawl';_g[_gamesCounter].path = 'chainbrawl.unity3d';_g[_gamesCounter].type = 'unity';_g[_gamesCounter].credits = 'Matthew Mitchell';_g[_gamesCounter].instructions = 'Knock the other players off the platform.';
_gamesCounter++;_g[_gamesCounter] = new Object();_g[_gamesCounter].name = 'The Game Of Trying Very Hard Not To Jump Because It Is Very Bad For You.';_g[_gamesCounter].path = 'The%20Game%20Of%20Trying%20Very%20Hard%20Not%20To%20Jump%20Because%20It%20Is%20Very%20Bad%20For%20You.unity3d';_g[_gamesCounter].type = 'unity';_g[_gamesCounter].credits = 'Jannick Petersen (jahy@itu.dk)';_g[_gamesCounter].instructions = 'Do not jump! Though if others jump it is good for you.';
_gamesCounter++;_g[_gamesCounter] = new Object();_g[_gamesCounter].name = 'Dragon Slayer 2002';_g[_gamesCounter].path = 'DragonSlayer2002.unity3d';_g[_gamesCounter].type = 'unity';_g[_gamesCounter].credits = '@lolinc_ @VildNinja';_g[_gamesCounter].instructions = 'Slay it!!!!!!!';
_gamesCounter++;_g[_gamesCounter] = new Object();_g[_gamesCounter].name = 'Medium';_g[_gamesCounter].path = 'medium.unity3d';_g[_gamesCounter].type = 'unity';_g[_gamesCounter].credits = 'Niels Justesen';_g[_gamesCounter].instructions = 'Middle numbers win! Use up/down.';
_gamesCounter++;_g[_gamesCounter] = new Object();_g[_gamesCounter].name = 'Lisboa Anno 1940';_g[_gamesCounter].path = 'lisboa.unity3d';_g[_gamesCounter].type = 'unity';_g[_gamesCounter].credits = '@joonturbo, @brammichielsen, @ongaku_mm, https://soundcloud.com/sorenandreasen';_g[_gamesCounter].instructions = 'Survival race with trains. [A] button to switch lanes (to the right). ';